services:
  redis:
    image: ${REDIS_IMAGE}
    container_name: ${REDIS_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    command: ["redis-server", "--appendonly", "${REDIS_APPENDONLY}"]
    volumes:
      - redis_data:/data
    expose:
      - "${REDIS_PORT}"
    networks:
      - ener-network

  backend:
    image: ${BACKEND_IMAGE}
    container_name: ${BACKEND_CONTAINER_NAME}
    restart: ${RESTART_POLICY}
    env_file:
      - /home/ubuntu/ener_quote/.env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_DB: ${REDIS_DB}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    ports:
      - "8000:${BACKEND_PORT}"
    networks:
      - ener-network

networks:
  ener-network:
    driver: bridge

volumes:
  redis_data: